"""empty message

Revision ID: 9324e6cac02d
Revises: None
Create Date: 2016-02-25 21:16:28.656597

"""

# revision identifiers, used by Alembic.
revision = '9324e6cac02d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteerroles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('preferred_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteers_email'), 'volunteers', ['email'], unique=True)
    op.create_index(op.f('ix_volunteers_phone'), 'volunteers', ['phone'], unique=True)
    op.create_table('kids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('preferred_name', sa.String(length=64), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kids_email'), 'kids', ['email'], unique=True)
    op.create_index(op.f('ix_kids_phone'), 'kids', ['phone'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kids_phone'), table_name='kids')
    op.drop_index(op.f('ix_kids_email'), table_name='kids')
    op.drop_table('kids')
    op.drop_index(op.f('ix_volunteers_phone'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_email'), table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_table('volunteerroles')
    op.drop_table('schools')
    ### end Alembic commands ###
